In [1]:
import numpy as np
import pandas as pd

### Employee csv files

In [2]:
Employees=pd.read_csv('employees.csv')
Employees.head(3)

   EmployeeID        Name Department Designation  Age  Gender       City
0           1  Employee_1         IT     Officer   23    Male     Mardan
1           2  Employee_2    Finance   Assistant   24  Female       Swat
2           3  Employee_3      Sales   Executive   25    Male  Islamabad

### Attendance csv files

In [3]:
attendance=pd.read_csv('attendance.csv')
attendance.head(3)

   EmployeeID Month  WorkingDays  PresentDays  AbsentDays
0           1  July           30           21           9
1           2  July           30           22           8
2           3  July           30           23           7

### Salary csv file

In [4]:
salary=pd.read_csv('salary.csv')
salary.head(3)

   EmployeeID  BasicSalary  Allowance  Deduction  NetSalary
0           1        35000       2500       1250      36250
1           2        40000       3000       1500      41500
2           3        45000       3500       1750      46750

## Clean missing values

In [5]:
Employees = Employees.dropna()

In [6]:
attendance=attendance.dropna()

In [7]:
salary=salary.dropna()

In [8]:
print(type(Employees))
print(type(attendance))
Employees = pd.read_csv("employees.csv")

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>

## Marge datasets

In [9]:
Employees_attendance = pd.merge(
    Employees,
    attendance,
    on='EmployeeID'
)

In [10]:
Final_data=pd.merge(
    Employees_attendance,
    salary,
    on='EmployeeID'
)

### Calculate present, absent, attendance percentage.

In [11]:
Final_data['AttendancePercentage'] = (Final_data['PresentDays'] / Final_data['WorkingDays']) * 100

In [12]:
Final_data[['EmployeeID', 'PresentDays', 'WorkingDays', 'AttendancePercentage']].head()

   EmployeeID  PresentDays  WorkingDays  AttendancePercentage
0           1           21           30             70.000000
1           2           22           30             73.333333
2           3           23           30             76.666667
3           4           24           30             80.000000
4           5           25           30             83.333333

In [13]:
Final_data.head()

,EmployeeID,Name,Department,Designation,Age,Gender,City,Month,WorkingDays,PresentDays,AbsentDays,BasicSalary,Allowance,Deduction,NetSalary,AttendancePercentage
0,1,Employee_1,IT,Officer,23,Male,Mardan,July,30,21,9,35000,2500,1250,36250,70.000000
1,2,Employee_2,Finance,Assistant,24,Female,Swat,July,30,22,8,40000,3000,1500,41500,73.333333
2,3,Employee_3,Sales,Executive,25,Male,Islamabad,July,30,23,7,45000,3500,1750,46750,76.666667
3,4,Employee_4,Marketing,Analyst,26,Female,Lahore,July,30,24,6,50000,4000,1000,53000,80.000000
4,5,Employee_5,HR,Manager,27,Male,Peshawar,July,30,25,5,55000,2000,1250,55750,83.333333

## Calculate Salary

In [14]:
#  daily salry
Final_data['daily_salary'] = Final_data['NetSalary'] / Final_data['WorkingDays']

In [15]:
# final salary
Final_data['Final_salary'] = Final_data['daily_salary']*Final_data['PresentDays']

In [16]:
Final_data.head()

,EmployeeID,Name,Department,Designation,Age,Gender,City,Month,WorkingDays,PresentDays,AbsentDays,BasicSalary,Allowance,Deduction,NetSalary,AttendancePercentage,daily_salary,Final_salary
0,1,Employee_1,IT,Officer,23,Male,Mardan,July,30,21,9,35000,2500,1250,36250,70.000000,1208.333333,25375.000000
1,2,Employee_2,Finance,Assistant,24,Female,Swat,July,30,22,8,40000,3000,1500,41500,73.333333,1383.333333,30433.333333
2,3,Employee_3,Sales,Executive,25,Male,Islamabad,July,30,23,7,45000,3500,1750,46750,76.666667,1558.333333,35841.666667
3,4,Employee_4,Marketing,Analyst,26,Female,Lahore,July,30,24,6,50000,4000,1000,53000,80.000000,1766.666667,42400.000000
4,5,Employee_5,HR,Manager,27,Male,Peshawar,July,30,25,5,55000,2000,1250,55750,83.333333,1858.333333,46458.333333

In [17]:
# Max salary

highest_salary=Final_data['Final_salary'].max()
highest_salary

np.float64(77750.0)

In [18]:
# lowest salary
lowest_salary=Final_data['Final_salary'].min()
lowest_salary

np.float64(20333.333333333332)

In [19]:
# average salary

average_salary=Final_data['Final_salary'].mean()
average_salary

np.float64(45051.48333333333)

### Department-wise Salary

In [20]:
Final_data.groupby('Department')['Final_salary'].mean()

Department
Finance      45038.083333
HR           35813.750000
IT           40397.083333
Marketing    54327.083333
Sales        49681.416667
Name: Final_salary, dtype: float64

In [21]:
Final_data[Final_data['AttendancePercentage']<80.0].head(10)

,EmployeeID,Name,Department,Designation,Age,Gender,City,Month,WorkingDays,PresentDays,AbsentDays,BasicSalary,Allowance,Deduction,NetSalary,AttendancePercentage,daily_salary,Final_salary
0,1,Employee_1,IT,Officer,23,Male,Mardan,July,30,21,9,35000,2500,1250,36250,70.000000,1208.333333,25375.000000
1,2,Employee_2,Finance,Assistant,24,Female,Swat,July,30,22,8,40000,3000,1500,41500,73.333333,1383.333333,30433.333333
2,3,Employee_3,Sales,Executive,25,Male,Islamabad,July,30,23,7,45000,3500,1750,46750,76.666667,1558.333333,35841.666667
10,11,Employee_11,IT,Officer,33,Male,Mardan,July,30,20,10,35000,2500,1750,35750,66.666667,1191.666667,23833.333333
11,12,Employee_12,Finance,Assistant,34,Female,Swat,July,30,21,9,40000,3000,1000,42000,70.000000,1400.000000,29400.000000
12,13,Employee_13,Sales,Executive,35,Male,Islamabad,July,30,22,8,45000,3500,1250,47250,73.333333,1575.000000,34650.000000
13,14,Employee_14,Marketing,Analyst,36,Female,Lahore,July,30,23,7,50000,4000,1500,52500,76.666667,1750.000000,40250.000000
21,22,Employee_22,Finance,Assistant,44,Female,Swat,July,30,20,10,40000,3000,1500,41500,66.666667,1383.333333,27666.666667
22,23,Employee_23,Sales,Executive,45,Male,Islamabad,July,30,21,9,45000,3500,1750,46750,70.000000,1558.333333,32725.000000
23,24,Employee_24,Marketing,Analyst,22,Female,Lahore,July,30,22,8,50000,4000,1000,53000,73.333333,1766.666667,38866.666667

# save final report in csv file

In [22]:
Final_data.to_csv("Final_Report.csv" , index=False)

In [23]:
# show final report

Final_Report=pd.read_csv("Final_Report.csv")
Final_Report.sample(10)

,EmployeeID,Name,Department,Designation,Age,Gender,City,Month,WorkingDays,PresentDays,AbsentDays,BasicSalary,Allowance,Deduction,NetSalary,AttendancePercentage,daily_salary,Final_salary
347,348,Employee_348,Sales,Executive,34,Female,Islamabad,July,30,27,3,70000,3500,1000,72500,90.000000,2416.666667,65250.000000
360,361,Employee_361,IT,Officer,23,Male,Mardan,July,30,29,1,35000,2500,1250,36250,96.666667,1208.333333,35041.666667
419,420,Employee_420,HR,Manager,34,Female,Peshawar,July,30,22,8,30000,2000,1000,31000,73.333333,1033.333333,22733.333333
329,330,Employee_330,HR,Manager,40,Female,Peshawar,July,30,20,10,30000,2000,1500,30500,66.666667,1016.666667,20333.333333
259,260,Employee_260,HR,Manager,42,Female,Peshawar,July,30,27,3,30000,2000,1000,31000,90.000000,1033.333333,27900.000000
102,103,Employee_103,Sales,Executive,29,Male,Islamabad,July,30,24,6,45000,3500,1750,46750,80.000000,1558.333333,37400.000000
261,262,Employee_262,Finance,Assistant,44,Female,Swat,July,30,29,1,40000,3000,1500,41500,96.666667,1383.333333,40116.666667
258,259,Employee_259,Marketing,Analyst,41,Male,Lahore,July,30,26,4,75000,4000,1750,77250,86.666667,2575.000000,66950.000000
409,410,Employee_410,HR,Manager,24,Female,Peshawar,July,30,23,7,30000,2000,1500,30500,76.666667,1016.666667,23383.333333
312,313,Employee_313,Sales,Executive,23,Male,Islamabad,July,30,25,5,45000,3500,1250,47250,83.333333,1575.000000,39375.000000

In [24]:
Final_data['daily_salary'] = Final_data['NetSalary'] / Final_data['WorkingDays']

Final_data['Final_salary'] = (
    Final_data['daily_salary'] * Final_data['PresentDays']
)